"""empty message

Revision ID: 333663927c11
Revises: fbd44d4cf0fe
Create Date: 2024-12-23 19:31:08.215876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333663927c11'
down_revision = 'fbd44d4cf0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_constraint('name_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.create_unique_constraint('name_name_key', ['name'])

    # ### end Alembic commands ###
